### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mattalexx** [BiteDasher/kesboot#1]
https://github.com/BiteDasher/kesboot/blob/936c6f152fb669bc130092a0acc15976f2b7718a/README.md?plain=1#L72

**Comment by BiteDasher** [comment]
> https://github.com/BiteDasher/kesboot/blob/936c6f152fb669bc130092a0acc15976f2b7718a/README.md?plain=1#L72

That is why it is crossed out. So far, I'm thinking about how to properly pack the archive with the program, but you can use the archive from the releases... And `install.sh`

**Comment by mattalexx** [comment]
Okay :-)

**Comment by JordanViknar** [comment]
You forgot to close the issue.

**Comment by BiteDasher** [comment]
> You forgot to close the issue.

Because it is not solved. I will work on this later

**Comment by BiteDasher** [comment]
@mattalexx fixed in 7968d85e0f1d0f0e2c1179874fc63fb34cea98bf
