### ISSUE TITLE
Adding second initramfs for microcode

### ISSUE THREAD

**Issue by liamstaras** [BiteDasher/kesboot#2]
Hi, I can't see an obvious way to add a second initramfs for microcode other than by inserting directly into the cmdline array. This is obviously not the preferable solution - if this functionality existed and I'm missing it or could be added that would be great. Many thanks!

**Comment by BiteDasher** [comment]
> Hi, I can't see an obvious way to add a second initramfs for microcode other than by inserting directly into the cmdline array. This is obviously not the preferable solution - if this functionality existed and I'm missing it or could be added that would be great. Many thanks!

https://github.com/BiteDasher/kesboot/commit/8aefdc340dec42c229b265131e2a2f16a4d88c59

Please try this and ping me if it worked

**Comment by liamstaras** [comment]
@BiteDasher Excellent - that seems to work perfectly. Thanks!
